### ISSUE TITLE
Add getting started instructions in the README.md (with composer support)

### ISSUE THREAD

**Issue by moul** [getmillipede/millipede-php#2]

**Comment by rockyluke** [comment]
Good idea !

**Comment by tusbar** [comment]
Good idea !

**Comment by moul** [comment]
Good idea !

**Comment by moul** [comment]
![](http://www.ntautogroup.com.au/sites/default/files/GoodIdea.jpg)

**Comment by tusbar** [comment]
![](http://dailypicksandflicks.com/wp-content/uploads/2011/06/Probably-not-a-good-idea.jpg)

**Comment by rockyluke** [comment]
it 's done.

**Comment by tusbar** [comment]
Thank you very much.
